version: '3'

services:
    teravoz:
        build: .
        user: node
        container_name: teravoz-client
        ports:
            - '3000:3000'
        volumes:
            - ./src:/usr/app/src:rw
        environment:
            PORT: 3000
            API_URL: teravoz:3000
            NODE_ENV: production
            NODE_PATH: ./src
            CALL_STORE_NAME: 'call'
            CUSTOMER_STORE_NAME: 'customer'
