version: '3'

services:
    teravoz:
        build: .
        user: node
        container_name: teravoz-client
        command: node src/server.js
        ports:
            - '3000:8080'
        volumes:
            - ./src:/usr/app/src:rw
        environment:
            DEBUG: service:*
            PORT: 8080
            NODE_ENV: production
            NODE_PATH: ./src
            CALL_STORE_NAME: 'call'
            CUSTOMER_STORE_NAME: 'customer'
