version: '3'

services:
    teravoz:
        build:
          dockerfile: Dockerfile.test
          context: .
        user: node
        container_name: teravoz-client-test
        volumes:
            - ./src:/usr/app/src:rw
        environment:
            NODE_ENV: test
            NODE_PATH: ./src
            CALL_STORE_NAME: 'call-test'
            CUSTOMER_STORE_NAME: 'customer-test'